version: '3'

services:
  core:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - envs/prod.env
    privileged: true
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - default
      - telehooks_mq
    command: python3 __main__.py

  postgres:
    restart: always
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - envs/prod.env

volumes:
  postgres_data: { }

networks:
  telehooks_mq:
    external: true
