version: '3'

services:
  core:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - envs/local.env
    privileged: true
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - default
      - telehooks_mq
    logging:
      options:
        max-size: "1mb"
        max-file: "3"
    command: make run

#  home_assistant:
#    restart: unless-stopped
#    container_name: homeassistant
#    image: homeassistant/home-assistant:2023.10
#    volumes:
#      - ./home_assistant_config:/config
#      - /etc/localtime:/etc/localtime:ro
#    privileged: true
#    ports:
#      - "8123:8123"

  postgres:
    restart: always
    image: postgres:14.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - envs/local.env

  zigbee_mq:
    restart: always
    image: eclipse-mosquitto:2.0.18
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

networks:
  telehooks_mq:
    external: true
