version: '3'

services:
  core:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - envs/local.env
    privileged: true
    volumes:
      - .:/app
      - /dev:/dev
    ports:
      - "8443:8443"
    command: python3 __main__.py
