[tool.poetry]
name = "security_guard"
version = "0.1.0"
description = ""
authors = ["expert_m"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23"
pytz = "^2021.1"
emoji = "^1.2.0"
pyserial = "^3.4"
#opencv-python = { version = "^4.2.0", optional = true }
imutils = "^0.5.3"
numpy = { version = "1.18.4", optional = true }
matplotlib = { version = "=3.3.0", optional = true }
seaborn = "^0.11.1"
sqlalchemy = "^1.3.23"
sentry-sdk = "^1.0.0"
dropbox = "^11.4.0"
openpyxl = "^3.0.3"
pytest = "^6.2.2"
fire = "^0.4.0"
wheel = "^0.37.0"
pandas = { version = "1.0.5", optional = true }
scipy = { version = "1.5.2", optional = true }
python-dotenv = "^0.19.0"
python-telegram-bot = "^13.8.1"
crontab = "^0.23.0"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
heavy = ["numpy", "matplotlib", "pandas", "scipy"]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
