[tool.poetry]
name = "security_guard"
version = "0.1.0"
description = ""
authors = ["expert_m"]

[tool.poetry.dependencies]
python = "^3.8"
schedule = "^1.0.0"
requests = "^2.23"
pytz = "^2021.1"
emoji = "^1.2.0"
pyserial = "^3.4"
#opencv-python = "4.2.0"
imutils = "^0.5.3"
numpy = "1.18.4"
python-telegram-bot = {version = "^13.0", extras = ["socks"]}
matplotlib = "=3.3.4"
seaborn = "^0.11.1"
sqlalchemy = "^1.3.23"
sentry-sdk = "^1.0.0"
dropbox = "^11.4.0"
openpyxl = "^3.0.3"
pytest = "^6.2.2"
fire = "^0.4.0"
wheel = "^0.36.2"
gpiozero = "^1.5.1"
pandas = "0.25.3"
scipy = "1.4.1"
python-dotenv = "^0.15.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
